# Generated by Django 4.1.1 on 2022-11-29 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileImage',
            field=models.ImageField(default='blank-profile-picture.png', upload_to='media'),
        ),
    ]
