# Generated by Django 4.1.1 on 2022-12-20 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_followerscount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followerscount',
            old_name='followers',
            new_name='follower',
        ),
    ]
